// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  /// Autogenerated return type of AddComment.
  static let AddCommentPayload = ApolloAPI.Object(
    typename: "AddCommentPayload",
    implementedInterfaces: [],
    keyFields: nil
  )
}