// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  /// Autogenerated return type of DeleteIssueComment.
  static let DeleteIssueCommentPayload = ApolloAPI.Object(
    typename: "DeleteIssueCommentPayload",
    implementedInterfaces: [],
    keyFields: nil
  )
}