// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  /// Autogenerated return type of DeleteIssue.
  static let DeleteIssuePayload = ApolloAPI.Object(
    typename: "DeleteIssuePayload",
    implementedInterfaces: [],
    keyFields: nil
  )
}