// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  /// Autogenerated return type of UpdateIssueComment.
  static let UpdateIssueCommentPayload = ApolloAPI.Object(
    typename: "UpdateIssueCommentPayload",
    implementedInterfaces: [],
    keyFields: nil
  )
}